# === WIFI consts

WIFI__SSID: str = "YOUR_WIFI_SSD"
WIFI__PASSWORD: str = "YOUR_WIFI_PASSWORD"
WIFI__TIMEOUT_SECONDS: int = 10

# === MQTT consts

MQTT__BROKER_ADDRESS: str = "YOUR_BROKER_ADDRESS"
MQTT__BROKER_PORT: int = 1883
MQTT__MY_CLIENT_ID: str = "YOUR_CLIENT_ID"
MQTT__MY_USERNAME: str = "YOUR_USERNAME"
MQTT__MY_PASSWORD: str = "YOUR_PASSWORD"
MQTT__MY_LAST_WILL_TOPIC: str = "YOUR/LAST/WILL/TOPIC"
MQTT__MY_LAST_WILL_MESSAGE: str = "YOUR MESSAGE"
MQTT__MODULE_SWITCH_TOPIC: str = "YOUR/MODULE/SWITCH/TOPIC"

# === MODULES ===

# === dashboard consts

DASHBOARD__MQTT_INPUT_TOPIC: str = "YOUR/DASHBOARD/INPUT/TOPIC"

# === clock consts

CLOCK__MQTT_MODE_SWITCH_TOPIC: str = "YOUR/CLOCK/MODE/SWITCH/TOPIC"
CLOCK__MQTT_BRIGHTNESS_SWITCH_TOPIC: str = "YOUR/CLOCK/BRIGHTNESS/SWITCH/TOPIC"