# === device consts

UTC_OFFSET: int = 0

# === WIFI consts

WIFI__SSID: str = "YOUR_WIFI_SSD"
WIFI__PASSWORD: str = "YOUR_WIFI_PASSWORD"
WIFI__TIMEOUT_SECONDS: int = 10

# === MQTT consts

MQTT__BROKER_ADDRESS: str = "YOUR_BROKER_ADDRESS"
MQTT__BROKER_PORT: int = 1883
MQTT__MY_CLIENT_ID: str = "YOUR_CLIENT_ID"
MQTT__KEEPALIVE_SECONDS: int = 60
MQTT__MY_USERNAME: str = "YOUR_USERNAME"
MQTT__MY_PASSWORD: str = "YOUR_PASSWORD"
MQTT__MY_LAST_WILL_TOPIC: str = "YOUR/LAST/WILL/TOPIC"
MQTT__MY_LAST_WILL_MESSAGE: str = "YOUR MESSAGE"
MQTT__MODULE_SWITCH_TOPIC: str = "YOUR/MODULE/SWITCH/TOPIC"
MQTT__WORKER_TOPIC: str = "YOUR/WORKER/TOPIC"

# === ENV sensor consts

ENV__TEMPERATURE_OFFSET: float = 0.0
ENV__HUMIDITY_OFFSET: float = 0.0

# === MODULES ===

# === biomet consts

# TODO: get rid of suffix/prefix logic, just hardcode it properly here
# TODO: rename rating to score
BIOMET__MQTT_IMAGE_RECEIVE_TOPIC: str = "YOUR/BIOMET/IMAGE/RECEIVE/TOPIC"
BIOMET__MQTT_RATING_RECEIVE_TOPIC: str = "YOUR/BIOMET/RATING/RECEIVE/TOPIC"
BIOMET__MQTT_IMAGE_REQUEST_WORKER_TOPIC_SUFFIX: str = "/YOUR/IMAGE/REQUEST/SUFFIX"
BIOMET__MQTT_MEDICAL_IMAGE_REQUEST_WORKER_TOPIC_SUFFIX: str = "/YOUR/MEDICAL/IMAGE/REQUEST/SUFFIX"
BIOMET__MQTT_PERSONAL_IMAGE_REQUEST_WORKER_TOPIC_SUFFIX: str = "/YOUR/PERSONAL/IMAGE/REQUEST/SUFFIX"
BIOMET__MQTT_RATING_REQUEST_WORKER_TOPIC_SUFFIX: str = "/YOUR/RATING/REQUEST/SUFFIX"
BIOMET__MQTT_RATING_SEND_WORKER_TOPIC_SUFFIX: str = "/YOUR/BIOMET/RATING/SEND/TOPIC/SUFFIX"

# === clock consts

CLOCK__MQTT_MODE_SWITCH_TOPIC: str = "YOUR/CLOCK/MODE/SWITCH/TOPIC"
CLOCK__MQTT_BRIGHTNESS_SWITCH_TOPIC: str = "YOUR/CLOCK/BRIGHTNESS/SWITCH/TOPIC"

# === dashboard consts

DASHBOARD__MQTT_INPUT_TOPIC: str = "YOUR/DASHBOARD/INPUT/TOPIC"

# === SERVICES ===

SERVICE__AUTO_BRIGHTNESS_DAY_BRIGHTNESS: int = 127
SERVICE__AUTO_BRIGHTNESS_NIGHT_BRIGHTNESS: int = 0
SERVICE__AUTO_BRIGHTNESS_DAY_START_HOUR: int = 7
SERVICE__AUTO_BRIGHTNESS_NIGHT_START_HOUR: int = 23
